name = "StippleLatex"
uuid = "8706c442-30ce-4f68-b407-b81ebf148be9"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"

[compat]
Genie = "1.18"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
