name = "StippleLatex"
uuid = "8706c442-30ce-4f68-b407-b81ebf148be9"
authors = ["Adrian Salceanu <e@essenciary.com>", "Helmut HÃ¤nnsel <helmut.haensel@gmx.de>"]
version = "0.5.8"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"

[compat]
Genie = "5"
Stipple = "0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
